spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: cami
    password: teste
  jpa:
    show-sql: true
    #hibernate:
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  springdoc-ui:
    path: /swagger-ui.html